image: docker:stable

stages:
  - build
  - test
  - build-image
  - deploy

build-project:
  image: maven:latest
  stage: build
  retry: 2
  before_script:
    - chmod +x mvnw
    - chmod +x .mvn
  script:
    - ./mvnw compile

test-project:
  image: maven:latest
  stage: test
  retry: 2
  dependencies:
    - build-project
  before_script:
    - chmod +x mvnw
    - chmod +x .mvn
  script:
    - ./mvnw test

build-docker:
  stage: build-image
  retry: 2
  dependencies:
    - test-project
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  tags:
    - executor-task
  script:
    - docker build -t gasmartins/smartpayment-customers .
    - docker push gasmartins/smartpayment-customers:latest