image: docker:stable

services:
  - docker:dind

stages:
  - compile
  - test
  - build
  - build-image
  - deploy

compile-project:
  stage: compile
  retry: 2
  before_script:
    - chmod +x mvnw
    - chmod +x .mvn
  script:
    - ./mvnw compile

test-project:
  stage: test
  retry: 2
  dependencies:
    - compile-project
  before_script:
    - chmod +x mvnw
    - chmod +x .mvn
  script:
    - ./mvnw test

build-project:
  stage: build
  retry: 2
  dependencies:
    - test-project
  before_script:
    - chmod +x mvnw
    - chmod +x .mvn
  script:
    - ./mvnw clean install -DskipTests

build-docker:
  stage: build-image
  retry: 2
  dependencies:
    - build-project
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t gasmartins/smartpayment-customers .
    - docker push gasmartins/smartpayment-customers:latest