version: "3.7"
services:
  mongodb:
    image: mongo:bionic
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=customersdb
    ports:
    - "27017:27017"
    - "28017:28017"
    networks:
      - smartpayment-network
  jaeger-server:
    image: jaegertracing/all-in-one:1.18.1
    container_name: "jaeger-server"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
    networks:
      - smartpayment-network
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: smartpayment-customers
    image: gasmartins/smartpayment-customers
    depends_on:
      - mongodb
      - jaeger-server
    links:
      - mongodb
      - jaeger-server
    networks:
      - smartpayment-network
    ports:
    - "8080:8080"
networks:
  smartpayment-network:
    driver: bridge

