spring:
    profiles:
        active: ${activatedProperties}
    data:
        mongodb:
            database: customersdb
    sleuth:
        opentracing:
            enabled: true
        sampler:
            probability: 1.0
        trace-id128: true
    

